---

- hosts: dbservers
  become: true
  vars_files:
    - vault/secrets.yml
  roles:
    - { role: common, tags: ["common"] }
    - { role: setup_docker, tags: ["docker", "containerization"] }
    - { role: open_port_5432, tags: ["firewall", "web"] }

