---

- hosts: webservers
  become: true
  vars_files:
    - vault/secrets.yml
  roles:
    - { role: common, tags: ["common"] }
    - { role: setup_docker, tags: ["docker", "containerization"] }
    - { role: open_port_80, tags: ["firewall", "web"] }
    - { role: open_port_443, tags: ["firewall", "web"] }

