---

- name: expire password
  command: chage -d 0 "{{ vault_admin_user }}"

- name: restart ssh
  systemd:
    name: ssh
    state: restarted
    daemon_reload: yes

- name: restart fail2ban
  systemd:
    name: fail2ban
    state: restarted
    daemon_reload: yes

- name: reload and restart apt timers
  command: systemctl daemon-reload && systemctl restart apt-daily-upgrade.timer

