---

- name: Expire password
  ansible.builtin.command: chage -d 0 "podman"

- name: Reload podman services
  ansible.builtin.systemd:
    name:
      - podman.socket
      - podman.service
    state: restarted
