---

- name: Disable SSH root login and password authentication
  ansible.builtin.template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0644'
  notify: Restart ssh

- name: Create admin group if needed
  ansible.builtin.group:
    name: "{{ vault_admin_user }}"
    state: present

- name: Ensure secondary 'admin' group exists
  ansible.builtin.group:
    name: admin
    state: present

- name: Create admin user with sudo privileges
  ansible.builtin.user:
    name: "{{ vault_admin_user }}"
    group: "{{ vault_admin_user }}"
    groups: admin,sudo
    append: true
    shell: /bin/bash
    password: "{{ vault_admin_password }}"
    create_home: true
    state: present
  notify: Expire password

- name: Create ssh directory for admin user
  ansible.builtin.file:
    path: "/home/{{ vault_admin_user }}/.ssh"
    state: directory
    owner: "{{ vault_admin_user }}"
    group: "{{ vault_admin_user }}"
    mode: '0700'

- name: Deploy authorized_keys for admin user
  ansible.builtin.authorized_key:
    user: "{{ vault_admin_user }}"
    key: "{{ vault_admin_ssh_public_key }}"

- name: Configure sudoers for admin user
  ansible.builtin.copy:
    dest: "/etc/sudoers.d/{{ vault_admin_user }}"
    content: "{{ vault_admin_user }} ALL=(ALL) ALL\n"
    owner: root
    group: root
    mode: '0440'

- name: Install fail2ban
  ansible.builtin.apt:
    name: fail2ban
    state: present
    update_cache: true

- name: Setup fail2ban jail.local
  ansible.builtin.template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: '0644'
  notify: Restart fail2ban

- name: Ensure fail2ban is running and enabled
  ansible.builtin.systemd:
    name: fail2ban
    state: started
    enabled: true

- name: Install UFW firewall
  ansible.builtin.apt:
    name: ufw
    state: present
    update_cache: true

- name: Allow SSH port through UFW
  community.general.ufw:
    rule: allow
    port: 22
    proto: tcp
  notify: Reload ufw

- name: Enable UFW firewall
  community.general.ufw:
    state: enabled

- name: Set timezone
  ansible.builtin.timezone:
    name: "UTC"

- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ hostname }}"

- name: Ensure Ansible remote_tmp directory exists with correct permissions
  ansible.builtin.file:
    path: /root/.ansible/tmp
    state: directory
    owner: root
    group: root
    mode: '0700'

- name: Ensure hostname is resolvable in /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1\s+{{ hostname }}$'
    line: "127.0.1.1 {{ hostname }}"
    state: present
    backup: true

- name: Install predetermined packages
  ansible.builtin.apt:
    name:
      - btop
      - vim
      - curl
      - git
      - debian-goodies
    state: present
    update_cache: true

- name: Install unattended-upgrades and apt-listchanges
  ansible.builtin.apt:
    name:
      - unattended-upgrades
      - apt-listchanges
    state: present
    update_cache: true

- name: Configure unattended-upgrades
  ansible.builtin.template:
    src: 99unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/99unattended-upgrades
    owner: root
    group: root
    mode: '0644'

- name: Enable and start unattended-upgrades service
  ansible.builtin.systemd:
    name: unattended-upgrades
    state: started
    enabled: true

- name: Ensure apt-daily-upgrade systemd override directory exists
  ansible.builtin.file:
    path: /etc/systemd/system/apt-daily-upgrade.timer.d
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Configure upgrade schedule (systemd override for apt-daily-upgrade.timer)
  ansible.builtin.template:
    src: apt-daily-upgrade-override.conf.j2
    dest: /etc/systemd/system/apt-daily-upgrade.timer.d/override.conf
    owner: root
    group: root
    mode: '0644'
  notify: Reload and restart apt timers
