all:
  children:
    dbservers:
      hosts: {}
    reverse_proxies:
      hosts: {}
    webservers:
      hosts:
        hetz-vps01:
          ansible_host: ryanjh.com
          host_aliases:
            - www.ryanjh.com

