all:
  children:
    dbservers:
      hosts: {}
    reverse_proxies:
      hosts: {}
    webservers:
      hosts:
        srv11:
          ansible_host: srv11.home.arpa
        srv30:
          ansible_host: srv30.home.arpa

